apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: falco-falcosidekick-scrape
  namespace: falco
  labels:
    prometheus: system-monitoring-prometheus
spec:
  staticConfigs:
    - labels:
        job: falco-falcosidekick
      targets:
        - falco-falcosidekick.falco:2801
