apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: falco-exporter-monitor
  namespace: falco
  labels:
    release: prometheus-operator
spec:
  endpoints:
    - port: http-web
    - path: /metrics
  namespaceSelector:
    matchNames:
      - falco
  selector:
    matchLabels:
      app.kubernetes.io/instance:  falco-exporter
      app.kubernetes.io/name: falco-exporter

